version: '2'
services:
  proxy:
   image: front-web:latest
   container_name: blockchain_proxy
   depends_on:
   - spring
   ports:
   - 80:80
   networks:
   - blockchain
  spring:
    image: back-web:latest
    container_name : blockchain_java
    depends_on:
    - db
    ports:
    - 8080:8080
    networks:
    - blockchain
  db:
    image: mysql:latest
    container_name: db_mysql
    ports: 
     - 3306:3306
    environment: 
     - MYSQL_ROOT_PASSWORD=mysql
     - MYSQL_DATABASE=blockchain
     - MYSQL_USER=blockchain
     - MYSQL_PASSWORD=mysql
    volumes:
     - my-database-volume:/var/lib/mysql
    networks:
      - blockchain
volumes:
  my-database-volume:
  my-elasticsearch-volume:
networks:
  blockchain:
